### ISSUE TITLE
Peace

### ISSUE THREAD

**Issue by Disastergirl** [davidfoerster/synesketch#1]
Change the world. Stop war.

**Comment by davidfoerster** [comment]
Please describe the behaviour of The World, that you perceive as faulty or sub-optimal, and the behaviour you expect it to have.

**Comment by Disastergirl** [comment]
![celestial 2](https://cloud.githubusercontent.com/assets/6481966/5608011/51ffd1ee-9473-11e4-999f-f2b4327264cc.jpg)
